### ISSUE TITLE
WMS layers not showing correct styling when loaded vector into QGIS

### ISSUE THREAD

**Issue by gavintaylorgis** [koordinates/koordinates-qgis-plugin#288] opened 2023-09-06 12:41 UTC
**Describe the bug**
When loading a WMS layer of a vector layer via the Koordinates plug-in in QGIS the layer is not appearing in the map viewer in the default style applied on the Koordinates website

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Plugin Panel
2. Select vector layer
3. Click on Add

**Expected behavior**
I expect the WMS layer to have the same styling as the default style on Koordinates cloud and the thumbnail visible in the plug-in

![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/49873801/69b2188e-39f1-4187-9acb-177ec434e9bc)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): Windows 10 Enterprise
 - QGIS, Kart & Plugin details:
Kart Plugin version
1.0.12
QGIS version
3.28.5-Firenze
Operating system
Windows 10 10.0.19045
Kart version
Kart v0.14.0, Copyright (c) Kart Contributors
Â» GDAL v3.6.3; PROJ v9.2.0; PDAL v2.5.3
Â» PyGit2 v1.12.1; Libgit2 v1.6.4; Git v2.34.0.windows.1.13.g93318cbc8d; Git LFS v3.3.0
Â» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.1; SpatiaLite v5.0.1; Libpq v15.0.3

**Comment by BallJonathan** [comment] 2023-09-06 21:27
Thanks Gavin. We have planned to fix this issue in the next major release. I'd expect it to be 1-2 months.

**Comment by BallJonathan** [comment] 2023-09-06 21:28
Duplicate of #283

**Comment by BallJonathan** [comment] 2023-10-25 03:12
@nyalldawson I dont see this working. Try testing on a layer like this https://data.mfe.govt.nz/layer/52375-lucas-nz-land-use-map-1990-2008-2012-2016-v011/

**Comment by nyalldawson** [comment] 2023-10-25 03:14
@BallJonathan I closed as it's a duplicate of #283 -- do we still need this one open?

**Comment by BallJonathan** [comment] 2023-10-25 03:19
Oh right. No. Apologies

**Closed by BallJonathan** 2023-10-25 03:19 UTC
Labels: bug
