### ISSUE TITLE
Data browser search box does not align to left hand margin

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#235] opened 2023-05-22 00:18 UTC
**Describe the bug**
Data browser search box does not align to left hand margin

**To Reproduce**
1. Open data browser
2. Note alignment of search box

**Expected behavior**
Search box should align to left hand edge of top tab bar, logo, search results etc

**Screenshots**

Proposed design:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/0ed5d923-854e-4e24-935e-08746027fe66)

Implementation:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/b45a2481-a26f-4491-a6d1-b2b1fe3e456a)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by BallJonathan** [comment] 2023-05-22 00:22
Duplicate of #209

**Closed** 2023-05-22 03:37 UTC
Labels: bug
