### ISSUE TITLE
Data browser filters cannot be closed by clicking outside

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#231] opened 2023-05-22 00:05 UTC
**Describe the bug**
Data browser filters cannot be closed by clicking outside

**To Reproduce**
1. Open a filter in the data browser
2. Click outside to close it
3. It doe not close

**Expected behavior**
- Data browser filters should close when the user clicks away from them

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/e00448c0-e9c3-4e23-9feb-d6a944e6b8f0)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by brentneave** [comment] 2023-05-22 00:11
Just noticed that the filters under the starred tab behave as expected and close when you click away from them. 
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/7200aea6-2fe2-4a52-82e8-0b16cb1cd7a9)

**Comment by BallJonathan** [comment] 2023-05-22 00:19
Duplicate of #212

**Closed** 2023-05-22 03:41 UTC
Labels: bug
