### ISSUE TITLE
Dataset cards do not match proposed design

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#236] opened 2023-05-22 00:21 UTC
**Describe the bug**
Dataset cards do not match proposed design

**To Reproduce**
1. View the data browser, starred items, my data or any place where data cards are displayed
2. Note that implementation does not match proposed design

**Expected behavior**
Dataset card implementation matches proposed design

**Screenshots**

Proposed design:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/10cacd48-3ca5-462f-9f0b-a47009a1dad0)
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/b770b8fd-8c2b-4cd6-82cc-817a3cd712d9)

Implementation:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/2b984e90-ef90-496a-bf2b-386d6186cc24)
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/678c3d96-8980-4ac1-84a9-6d03fcf21b99)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by nyalldawson** [comment] 2023-05-22 03:37
Closing as by designed

**Closed by nyalldawson** 2023-05-22 03:37 UTC
Labels: bug
