### ISSUE TITLE
AttributeError: ‘Koordinates’ object has no attribute ‘screen’

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#168] opened 2022-11-24 20:16 UTC
**Describe the bug**
Unable to load plugin. The follow error is received:
`Couldn’t load plugin ‘koordinates’ due to an error when calling its initGui() method
AttributeError: ‘Koordinates’ object has no attribute ‘screen’
Traceback (most recent call last):
File “/usr/lib/python3/dist-packages/qgis/[utils.py](http://utils.py/)”, line 448, in startPlugin
plugins[packageName].initGui()
File “/home/administrator/.local/share/QGIS/QGIS3/profiles/default/python/plugins/koordinates/[plugin.py](http://plugin.py/)”, line 29, in initGui
self.dock = Koordinates()
File “/home/administrator/.local/share/QGIS/QGIS3/profiles/default/python/plugins/koordinates/gui/[koordinates.py](http://koordinates.py/)”, line 415, in __init__
if [os.name](http://os.name/) == ‘nt’ or self.screen().devicePixelRatio() > 1:
AttributeError: ‘Koordinates’ object has no attribute ‘screen’
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad
Python Path:
/usr/share/qgis/python
/home/administrator/.local/share/QGIS/QGIS3/profiles/default/python
/home/administrator/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/[python38.zip](http://python38.zip/)
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/administrator/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/administrator/.local/share/QGIS/QGIS3/profiles/default/python`

Another user has reported similar 
`Couldn’t load plugin ‘koordinates’ due to an error when calling its
initGui() method
AttributeError: ‘Koordinates’ object has no attribute ‘screen’
Traceback (most recent call last):   File
“/usr/lib/python3/dist-packages/qgis/utils.py”, line 448, in startPlugin
    plugins[packageName].initGui()   File
“/home/greg/.local/share/QGIS/QGIS3/profiles/default/python/plugins/koordinates/plugin.py”,
line 29, in initGui     self.dock = Koordinates()   File
“/home/greg/.local/share/QGIS/QGIS3/profiles/default/python/plugins/koordinates/gui/koordinates.py”,
line 415, in __init__     if [os.name](http://os.name/) == ‘nt’ or
self.screen().devicePixelRatio() > 1: AttributeError: ‘Koordinates’
object has no attribute ‘screen’
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] QGIS
version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad
Python Path:
/home/***/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs
/usr/share/qgis/python
/home/***/.local/share/QGIS/QGIS3/profiles/default/python
/home/***/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/***/.local/share/QGIS/QGIS3/profiles/default/python
/home/***/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer`

**Comment by pfw** [comment] 2022-11-24 23:04
Could we get a screenshot of the 'About' dialog for QGIS? It should look something like this image

<img width="903" alt="Screenshot 2022-11-25 at 10 03 59 am" src="https://user-images.githubusercontent.com/92163/203872584-b426fcb2-13c4-4ec1-bee0-94537ffe36c3.png">

**Comment by nyalldawson** [comment] 2022-11-25 02:45
Caused by running on Qt < 5.14.

**Comment by pfw** [comment] 2022-11-25 03:37
That's what I thought from the QT docs but the logs mention 3.26.3-Buenos Aires which is at least that version I thought?

**Comment by pfw** [comment] 2022-11-25 03:37
Or... is that a Linux packaging thing where it gets a system version which is older?

**Comment by nyalldawson** [comment] 2022-11-25 03:47
Definitely looks like a linux or mac install, from the /home/* paths mentioned in the log. So if it is linux then yes, it'll be whatever the system Qt version is.

**Comment by nyalldawson** [comment] 2022-11-25 03:47
Just to clarify -- I can work around this

**Comment by pfw** [comment] 2022-11-25 04:17
Looks like Linux given it's compiled with gcc and uses /home, MacOS is /Users.

Excellent on the workaround - it does alarm me though that the QGIS required version isn't quite all that is needed. How best do we manage this going forward where we specify eg. 3.22 but that itself isn't enough to show that something will be working.

**Comment by nyalldawson** [comment] 2022-11-25 04:35
@pfw 

3.22 had a hard limit of QT 5.12 or above -- so we can use that as the baseline. (It refuses to compile with earlier versions)

**Comment by pfw** [comment] 2022-11-25 04:36
Ok, great. I think I saw that the 3.22 docker image issue was resolved, I'll check that out and if so turn on the tests for that as well.

**Comment by pfw** [comment] 2022-12-01 03:51
@BallJonathan There is a fix for this in now but will need a new build to go out.

**Closed** 2022-12-07 03:43 UTC
Labels: bug
