### ISSUE TITLE
Browse filters that should display data display no results

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#230] opened 2023-05-21 23:56 UTC
**Describe the bug**
Browse filters that should display data display no results

**To Reproduce**
1. Go to the Browse tab
2. Apply the Data Type › Vectors filter
3. The data browser shows “No data available”, although there should be data available

**Expected behavior**
- Vector datasets are displayed

**Screenshots**

QGIS plugin:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/24913c83-4094-4b7b-ae1a-8a954a11c75a)

Koordinates.com:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/3363d3ec-9732-432c-9200-1c28269eb629)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4
```

**Comment by nyalldawson** [comment] 2023-05-22 04:05
Only kicks in after applying and clearing various filters

**Comment by nyalldawson** [comment] 2023-06-06 04:23
I can't reproduce this anymore

**Comment by nyalldawson** [comment] 2023-06-19 23:55
Closing for now, please re-open if you can reproduce on latest version

**Closed by nyalldawson** 2023-06-19 23:55 UTC
Labels: bug, question
