### ISSUE TITLE
Explore tab incorrectly labelled as Browse

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#228] opened 2023-05-21 23:47 UTC
**Describe the bug**
Explore tab incorrectly labelled as Browse.

**To Reproduce**
1. Open the plugin
2. Note the Browse tab label

**Expected behavior**
Browse tab should be labelled “Explore”

**Screenshots**
Proposed design:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/d076477a-c605-44ea-a55e-ee89f2d17c26)

Implementation:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/50c1eb70-e849-464b-bcda-3def1bd533af)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS 
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by BallJonathan** [comment] 2023-05-21 23:49
duplicate of #206

**Closed** 2023-05-22 03:49 UTC
Labels: bug
